### ISSUE TITLE
New version of PYLINT issues warning

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#233]
```
************* Module collectives.api
collectives\api.py:172:7: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
collectives\api.py:400:7: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
************* Module collectives.forms.auth
collectives\forms\auth.py:66:8: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
************* Module collectives.routes.administration
collectives\routes\administration.py:41:12: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
collectives\routes\administration.py:41:24: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
************* Module collectives.routes.auth
collectives\routes\auth.py:127:21: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
```

Checks are failing due to a new version of pylint (2.5.0) which issue a warning if an fstring is used without reason.

**Comment by jnguiot** [comment]
On obtient aussi cette erreur: 
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.6/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/lint/run.py", line 338, in __init__
    linter.check(args)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 904, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
    check_astroid_module(ast_node)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
    walker.walk(ast_node)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pylint/checkers/variables.py", line 1177, in visit_import
```

**Comment by jnguiot** [comment]
Regarding the stacktrace, I have open a bug on pylint project. Our problem seems linked with dkim:
https://github.com/PyCQA/pylint/issues/3540
