### ISSUE TITLE
Erreur 500 lors de l'activation d'un compte sans email saisi côté extranet FFCAM

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#326]
Un adhérent peut avoir une licence au club sans avoir saisi d'adresse mail.
Lorsqu'il tente de créer son compte sur le site des collectives, une erreur 500 est générée.

L'erreur se reproduit systématiquement et a notamment été générée le 14 juillet vers 15h30.

Il faudrait si possible afficher un message du genre "Vous n'avez pas saisi d'adresse mail lors de votre adhésion au club. Envoyez un mail à secretariat@cafannecy.fr afin de demander que votre compte sur la FFCAM soit mis à jour avec votre adresse mail. Une fois fait, vous pourrez alors activer votre compte"

**Comment by jnguiot** [comment]
L'erreur qu'on a est la suivante: 
```
Jul 14 15:24:56 collectives python3[994]: ERROR:collectives:Exception on /auth/signup [POST]
Jul 14 15:24:56 collectives python3[994]: Traceback (most recent call last):
Jul 14 15:24:56 collectives python3[994]:   File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Jul 14 15:24:56 collectives python3[994]:     response = self.full_dispatch_request()
Jul 14 15:24:56 collectives python3[994]:   File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Jul 14 15:24:56 collectives python3[994]:     rv = self.handle_user_exception(e)
Jul 14 15:24:56 collectives python3[994]:   File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Jul 14 15:24:56 collectives python3[994]:     reraise(exc_type, exc_value, tb)
Jul 14 15:24:56 collectives python3[994]:   File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Jul 14 15:24:56 collectives python3[994]:     raise value
Jul 14 15:24:56 collectives python3[994]:   File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Jul 14 15:24:56 collectives python3[994]:     rv = self.dispatch_request()
Jul 14 15:24:56 collectives python3[994]:   File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Jul 14 15:24:56 collectives python3[994]:     return self.view_functions[rule.endpoint](**req.view_args)
Jul 14 15:24:56 collectives python3[994]:   File "/home/production/collectives-flask2/collectives/routes/auth.py", line 341, in signup
Jul 14 15:24:56 collectives python3[994]:     and user.mail.lower() == user_info.email.lower()
Jul 14 15:24:56 collectives python3[994]: AttributeError: 'NoneType' object has no attribute 'lower'```
