### ISSUE TITLE
[Robustesse] Vérifier si la date d'expiration de la licence n'est pas null

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#376]
Traces vues dans les logs

```
2020-11-08 12:15:55,712 ERROR root waitress : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/production/collectives-flask2/collectives/routes/event.py", line 184, in index
    filtered_activity=filtered_activity,
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/templating.py", line 136, in render_template
    ctx.app.update_template_context(context)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 838, in update_template_context
    context.update(func())
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/utils.py", line 379, in _user_context_processor
    return dict(current_user=_get_user())
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/login_manager.py", line 329, in _load_user
    user = self._load_user_from_remember_cookie(cookie)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/login_manager.py", line 372, in _load_user_from_remember_cookie
    user = self._user_callback(user_id)
  File "/home/production/collectives-flask2/collectives/routes/auth.py", line 46, in load_user
    if user is None or not user.is_active:
  File "/home/production/collectives-flask2/collectives/models/user.py", line 588, in is_active
    return self.enabled and self.check_license_valid_at_time(current_time())
  File "/home/production/collectives-flask2/collectives/models/user.py", line 351, in check_license_valid_at_time
    return self.license_expiry_date > time.date()
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.date'
2020-11-08 12:15:55,725 WARNING collectives waitress : Error in flask-statistics teardown: '_AppCtxGlobals' object has no attribute 'request_content_size' datefmt=
```

**Comment by fberu** [comment]
Cette erreur apparaît lorsque je suis obligé de créer un compte manuellement car l’adhérent ne reçoit jamais le mail lorsqu’il crée son compte. 

Lorsque je crée manuellement le compte, impossible de saisir une date d’expiration. En plus de catcher l’erreur il serait bien en plus de pouvoir indiquer une date d’expiration lors de la création d’un compte de test

**Comment by gdaviet** [comment]
A mon avis créer des compte de tests pour ces cas là  n’est pas une
solution viable, ça risque de poser des problèmes de desynchro dans le
futur.
Ce serait plus safe de regenerer un lien de confirmation manuellement et de
le transmettre à l’adhérent, je peux créer une UI dans l’administration
pour ça


Bon, cela dit ça ne ferait pas de mal de catcher l’erreur quand même

**Comment by fberu** [comment]
Pouvoir générer un lien me va aussi très bien!

**Comment by jnguiot** [comment]
@gdaviet est-ce que tu prends l'action?

**Comment by gdaviet** [comment]
Ok, je me l'assigne
