### ISSUE TITLE
[Import collectives] Erreur 500 si la donnée est plus longue que la taille de la colonne en BDD

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#379]
Une erreur 500 est générée lors de l'import de collectives si la donnée est plus grande que la taille de la colonne en BDD

Il faudrait catcher l'erreur.

```
2020-12-11 20:00:23,310 ERROR root waitress : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/production/collectives-flask2/collectives/routes/activity_supervison.py", line 144, in csv_import
    file.stream, activity_type, form.description.data
  File "/home/production/collectives-flask2/collectives/utils/csv.py", line 169, in process_stream
    db.session.commit()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
    self._assert_active(prepared_ok=True)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
    code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.DataError) (1406, "Data too long for column 'title' at row 1")
```

**Comment by jnguiot** [comment]
On a prévu des titres de 100 caractères de long maximum. Quelles taille maximale devrait-on donner aux titres?

**Comment by fberu** [comment]
@jnguiot ce que propose @gdaviet , à savoir tronquer, me va très bien :+1:

**Comment by fberu** [comment]
Ticket corrigé dans #390 . Je ferme le ticket
