### ISSUE TITLE
Paiement en ligne: Erreur 500 pour procéder au paiement en ligne lorsque le paiement est en attente

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#404]
Lorsque le paiement en ligne est en attente (je ne saurais plus trop dire comment je suis arrivé à cet état là), une erreur 500 est générée lorsqu'on clique sur le message "Procéder au paiement de ..."

Voir pour exemple la sortie https://test.collectives.cafannecy.fr/collectives/228-la-tulle

Les logs
```
2021-02-07 17:57:07,231 ERROR root waitress : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/demo/collectives-flask2/collectives/utils/access.py", line 54, in decorated_function
    return f(*args, **kwargs)
  File "/home/demo/collectives-flask2/collectives/routes/payment.py", line 418, in request_payment
    abort(500)
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/werkzeug/exceptions.py", line 772, in abort
    return _aborter(status, *args, **kwargs)
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/werkzeug/exceptions.py", line 753, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by gdaviet** [comment]
A priori c'était un lien plus valide, en gros tant que le paiement en ligne n'a pas été finalisé la page d'événement contient un lien "procéder au paiement" (au cas ou l'utilisateur ait fermé l'onglet Payline et souhaite y revenir). Mais une fois le paiement validé ou annulé ce lien n'est plus valide, et donne une erreur 500 (voulue).
@fberu tu penses que ca peut correspondre à comment tu en es arrivé là ?

On pourrait mettre un message d'erreur plus joli, mais si c'est bien ca le bug n'est pas critique

**Comment by fberu** [comment]
@gdaviet ce bug date et j'ai tardé à te répondre :(
Oui de mémoire ça ressemble bien à ça: le lien avait dû bien expirer

**Comment by gdaviet** [comment]
En théorie le problème a été résolu dans la dernière release
