### ISSUE TITLE
L'ajout d'un encadrant alors qu'il est inscrit à la collective génère une erreur 500 et quelques effets de bord

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#411]
J'ai une collective dont je suis l'encadrant.
Un encadrant s'inscrit à ma collective.
Finalement, je mets cet encadrant comme responsable de la collective et me supprime de l'encadrement. Cela génère une erreur 500.
Logs:
```
2021-03-31 14:20:39,618 ERROR collectives waitress : Exception on /collectives/1347/edit [POST] datefmt=
Traceback (most recent call last):
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/utils/access.py", line 54, in decorated_function
    return f(*args, **kwargs)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/utils/access.py", line 54, in decorated_function
    return f(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/routes/event.py", line 451, in manage_event
    db.session.add(event)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1981, in add
    self._save_or_update_state(state)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2000, in _save_or_update_state
    self._save_or_update_impl(st_)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2346, in _save_or_update_impl
    self._update_impl(state)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2320, in _update_impl
    "to the transient state." % state_str(state)
sqlalchemy.exc.InvalidRequestError: Instance '<Registration at 0x7fde88d59710>' has been deleted.  Use the make_transient() function to send this object back to the transient state.
2021-03-31 14:20:39,777 ERROR root waitress : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/utils/access.py", line 54, in decorated_function
    return f(*args, **kwargs)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/utils/access.py", line 54, in decorated_function
    return f(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/routes/event.py", line 451, in manage_event
    db.session.add(event)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1981, in add
    self._save_or_update_state(state)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2000, in _save_or_update_state
    self._save_or_update_impl(st_)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2346, in _save_or_update_impl
    self._update_impl(state)
  File "/home/production/collectives-flask2/.env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2320, in _update_impl
    "to the transient state." % state_str(state)
sqlalchemy.exc.InvalidRequestError: Instance '<Registration at 0x7fde88d59710>' has been deleted.  Use the make_transient() function to send this object back to the transient state.
```
Je reviens sur la collective, le message expliquant que l'inscrit devenu encadrant a été désinscrit (je n'ai plus le message exact) s'affiche.
Une fois la popup fermée, l'écran se rafraîchit et l'inscrit devenu encadrant est bien le seul encadrant mais apparaît en double
![image](https://user-images.githubusercontent.com/59260805/113143873-f1ed2900-922c-11eb-8ee7-5485cbd48be9.png)

L'enregistrement de la collective se passe correctement et toutes les informations affichées sont correctes

**Comment by gdaviet** [comment]
@fberu je viens de pousser un fix, peux-tu me confirmer que tu ne peux plus reproduire l'erreur sur test.collectives?

**Comment by fberu** [comment]
@gdaviet yes tout bon, merci! :)
