### ISSUE TITLE
Impossible to update DB

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#443]
New Db cannot be created.

Steps to repoduce: use sqlite
* remove app.db
* execute: ```export FLASK_APP="collectives:create_app"
flask db upgrade```
 
Observed behavior:
- we have an unexpected warning: 
``` 
c:\users\xxx\documents\git\collectives\.env\lib\site-packages\alembic\ddl\sqlite.py:43: UserWarning: Skipping unsupported ALTER for creation of implicit constraintPlease refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.
```
- a seconde upgrade throw an exception: 
``` 
Traceback (most recent call last):
  File "c:\users\xed.laptop-hgda0dlb\documents\git\collectives\.env\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\users\xed.laptop-hgda0dlb\documents\git\collectives\.env\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: duplicate column name: parent_event_id
```

Expected behavior:
- upgrade should not have warning
- redo an upgrade should not fail

Version: f062020752e5835b6326cace7d8ddb21e526be90

**Comment by jnguiot** [comment]
Issue has been introduced by af0eaab5fd4488f53a0457b7ec4e783f00a60670

**Comment by jnguiot** [comment]
Ce problème de se reproduit pas sur la préprod (surement grace à mysql)

**Comment by jnguiot** [comment]
To get rid of the warning:
```
diff --git a/migrations/versions/92edd5d709ec_add_self_registration_flag.py b/migrations/versions/92edd5d709ec_add_self_registration_flag.py
index 602e9da..73f1e6b 100644
--- a/migrations/versions/92edd5d709ec_add_self_registration_flag.py
+++ b/migrations/versions/92edd5d709ec_add_self_registration_flag.py
@@ -18,7 +18,8 @@ depends_on = None

 def upgrade():
     # ### commands auto generated by Alembic - please adjust! ###
-    op.add_column('registrations', sa.Column('is_self', sa.Boolean(), nullable=False, server_default="1"))
+    with op.batch_alter_table("registrations") as batch_op:
+        batch_op.add_column( sa.Column('is_self', sa.Boolean(), nullable=False, server_default="1"))
     op.add_column('payments', sa.Column('processor_url', sa.String(length=255), nullable=True))
     # ### end Alembic commands ###
```

**Comment by jnguiot** [comment]
Le problème vient du fait que lors de l'application du patch `3529f70521c4`, cette version n'est pas enregistrée dans la table `alembic_version`. Donc flask migrate tente de le réappliquer, d'où l'erreur
