### ISSUE TITLE
Erreur 500 lorsqu'on supprime un tarif alors qu'il y a un inscrit en attente de paiement

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#451]
Exemple sur https://test.collectives.cafannecy.fr/collectives/245-inscription

J'ai créé une collective. Ajouter un tarif. Ajouter un inscrit à la main => l'adhérent est donc inscrit en attente de paiement.
Puis j'ai supprimé le tarif. Depuis la collective est inaccessible et génère une erreur 500:

```
2021-08-05 14:08:53,972 ERROR root waitress : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/demo/collectives-flask2/collectives/utils/access.py", line 54, in decorated_function
    return f(*args, **kwargs)
  File "/home/demo/collectives-flask2/collectives/routes/event.py", line 246, in view_event
    payment_item_choice_form=payment_item_choice_form,
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/demo/collectives-flask2/collectives/templates/event.html", line 4, in top-level template code
    {% import 'macros.html' as macros with context %}
  File "/home/demo/collectives-flask2/collectives/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/demo/collectives-flask2/collectives/templates/event.html", line 114, in block "content"
    {% include 'partials/event/payment_item_choice.html' %}
  File "/home/demo/collectives-flask2/collectives/templates/partials/event/payment_item_choice.html", line 2, in top-level template code
    {% if payment_item_choice_form.item_price.choices | length %}
  File "/home/demo/collectives-flask2/.env/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'item_price'
```
Selon il faudrait interdire la suppression d'un tarif s'il y au moins 1 inscrit ayant payé ou 1 inscrit en attente de paiement

**Comment by gdaviet** [comment]
Ok, j'imagine que ca se produit lorsque l'on supprime le dernier tarif (donc que la collective repasse gratuite)
Dans ce cas on peut au choix:
 - interdire la suppression de ce tarif, comme tu le proposes
 - passer automatiquement tous les inscrits en attente de paiement à "Confirmé"

Niveau dev c'est à peu près la même chose, @fberu que préfères tu dans l'absolu?

**Comment by fberu** [comment]
@gdaviet passer la collective en gratuite me paraît périlleux niveau remboursement.
Donc je suis plus sur interdire une suppression de tarif dès qu’un adhérent a fait un paiement dessus. Si aucun paiement réalisé, pas de soucis pour supprimer

**Comment by gdaviet** [comment]
Ce cas ne peut se produire que si aucun paiement n'a été effectué; a partir du moment ou un paiement a été fait, on ne peut déjà plus supprimer le tarif.
Donc c'est vraiement juste pour le cas ou il n'y a que des paiements en attente mais aucun d'effectif
