### ISSUE TITLE
Extranet FFCAM injoignable

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#533]
Depuis le 29/08 environ, les actions sur l'extranet ne fonctionnent plus sur prod, preprod et environnement de dev.

```2022-08-30 13:12:01,467 ERROR root waitress-1 : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/demo/collectives-flask2/collectives/routes/auth.py", line 332, in signup
    license_info = extranet.api.check_license(license_number)
  File "/home/demo/collectives-flask2/collectives/utils/extranet.py", line 236, in check_license
    self.init()
  File "/home/demo/collectives-flask2/collectives/utils/extranet.py", line 206, in init
    soap_client = SoapClient(wsdl=config["EXTRANET_WSDL"])
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pysimplesoap/client.py", line 169, in __init__
    self.services = wsdl and self.wsdl_parse(wsdl, cache=cache)
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pysimplesoap/client.py", line 862, in wsdl_parse
    services = self._xml_tree_to_services(wsdl, cache, force_download)
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pysimplesoap/client.py", line 614, in _xml_tree_to_services
    preprocess_schema(schema, imported_schemas, elements, self.xsd_uri,
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pysimplesoap/helpers.py", line 441, in preprocess_schema
    process_element(elements, element_name, children, element_type,
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pysimplesoap/helpers.py", line 195, in process_element
    for a in e.children():
TypeError: 'NoneType' object is not iterable```

**Comment by jnguiot** [comment]
Il semble que ce soit dû à une modification du WSDL de la FFCAM. Notamment, ces passages provoquent des erreurs:

```
      <xsd:complexType name="ffcam_clubs">
        <xsd:all>
          <xsd:element name="collection" type="soap-enc:Array"/>
        </xsd:all>
      </xsd:complexType>
```

Notamment car  `collection` est un array sans element en dessous.

Cependant, le WSDL a l'air validde (testé avec d'autres outils en ligne. Il est donc probable que ce soit un bug de `pysimplesoap` .

**Comment by jnguiot** [comment]
`pysimplesoap` n'est plus maintenu depuis 5 ans.

La seule librairie encore un peu maintenue est `zeep` . Je vais donc l'implémenter...

**Comment by jnguiot** [comment]
En attendant le déploiement du patch sur la prod, j'utilise l'ancien wsdl sur la prod: 
```
EXTRANET_WSDL="https://extranet-clubalpin.com/app/soap/2022/extranet_pro.wsdl"
```

**Comment by jnguiot** [comment]
L'ancien wsdl n'a pas marché
