### ISSUE TITLE
Erreur 500 sur "Liste des inscrits" / export excel

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#565]
L'export des inscrits via le bouton "Liste des inscrits" génère une erreur 500.

```
2022-10-14 19:21:59,861 ERROR root waitress-3 : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/utils/access.py", line 57, in decorated_function
    return function(*args, **kwargs)
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/utils/access.py", line 57, in decorated_function
    return function(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/routes/event.py", line 275, in export_list_of_registered_users
    return send_file(
TypeError: send_file() got an unexpected keyword argument 'attachment_filename'
```

**Comment by jnguiot** [comment]
En effet, depuis la mise à jour de flask, il faut mettre `download_name`au lieu de `attachment_filename`
