### ISSUE TITLE
Erreur 500 sur paiement en ligne

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives#568]
Je n'ai pas réussi à reproduire mais plusieurs personnes se plaignent d'erreur 500 lorsqu'ils tente un paiement en ligne.
Exemple sur https://collectives.cafannecy.fr/collectives/4643-soiree-raclette-romaine

La trace qu'on peut voir dans les logs

```
2022-10-17 19:53:55,932 ERROR root waitress-8 : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/utils/access.py", line 57, in decorated_function
    return function(*args, **kwargs)
  File "/home/production/collectives-flask2/collectives/routes/event.py", line 679, in select_payment_item
    and not registration.unsettled_payments()
AttributeError: 'NoneType' object has no attribute 'unsettled_payments'

```

**Comment by jnguiot** [comment]
@fberu  j'ai regardé, mais je ne comprends pas le code. Peux-tu me donner un exemple de collective qui ne marche pas?

**Comment by jnguiot** [comment]
Ca plante ici: https://github.com/Club-Alpin-Annecy/collectives/blob/5c713f9ba7dd9ad125d11745d7a48e2729f6c990/collectives/routes/event.py#L679

**Comment by jnguiot** [comment]
La régression a été introduite par le commit 7ade28fc3a1ffd3d23e65a734575f6d9b0b70e98

``` 
@@ -636,9 +643,12 @@ def select_payment_item(event_id):

         # Find associated registration which is pending payment but
         # with no currently unsettled payments
-        for r in event.existing_registrations(current_user):
-            if r.is_pending_payment() and not r.unsettled_payments():
-                registration = r
+        for existing_registration in event.existing_registrations(current_user):
+            if (
+                existing_registration.is_pending_payment()
+                and not registration.unsettled_payments()
+            ):
+                registration = existing_registration
```

Je vais corriger
