### ISSUE TITLE
Erreur lors de l’enregistrement d’un nouvel équipement d’un nouveau modèle

### ISSUE THREAD

**Issue by IsabelleSo** [Club-Alpin-Annecy/collectives#585]
**Module Matériel**

Je créé un nouveau modèle (dans l'exemple le "Piolet droit 54cm") .
Je créé un équipement de ce modèle (en allant dans Gestion du matériel > Stock puis "Ajouter").
Lorsque j’enregistre, j’ai un message d’erreur « 500 Erreur sur le serveur ».
Si je modifie le modèle par un autre (créé plus anciennement), il n’y a pas d’erreur.

![image](https://user-images.githubusercontent.com/117855567/201673105-eec806ce-619d-48d6-9d05-58f54510554b.png)
![image](https://user-images.githubusercontent.com/117855567/201673161-bef84416-4aec-493c-b949-1dde24bf5f37.png)

Malgré cette erreur, l’équipement est présent dans la liste des équipements.

![image](https://user-images.githubusercontent.com/117855567/201673351-edff1cdb-6d6d-447f-a719-95708722f7f9.png)
![image](https://user-images.githubusercontent.com/117855567/201673401-f4360cc3-7189-49da-974d-3c3f9d1145cf.png)

**Comment by gdaviet** [comment]
L'erreur se produit sous MariaDB uniquement. 

```
(reference_prefix)s, %(path_img)s, %(price)s, %(deposit)s)]
[parameters: {'last_reference': 0, 'name': 'Piolet technique', 'reference_prefix': 'PT', 'path_img': None, 'price': Decimal('10'), 'deposit': Decimal('2')}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-03-08 21:13:34,725 ERROR root waitress-1 : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/demo/collectives-flask2/.env/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '0' for key 'UK_last_reference'")
```

Cela semble dû au champ `last_reference` défini comme unique dans le schéma DB:
```
        batch_op.create_unique_constraint("UK_last_reference", ["last_reference"])
```

Cette contrainte devrait probablement être supprimée

**Comment by gdaviet** [comment]
Fixed in #613
