### ISSUE TITLE
Image thumbnail generation fails due to FlaskImages  timezone issue 

### ISSUE THREAD

**Issue by gdaviet** [Club-Alpin-Annecy/collectives#590]
Vu dans les logs:

```
2022-11-15 17:36:11,610 ERROR collectives waitress-9 : Exception on /imgsizer/event-4841.jpeg [GET] datefmt=
Traceback (most recent call last):
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/production/collectives-flask2/.env/lib/python3.9/site-packages/flask_images/core.py", line 357, in handle_request
    if request.if_modified_since and request.if_modified_since >= mtime:
TypeError: can't compare offset-naive and offset-aware datetimes
2022-11-15 17:36:11,927 ERROR root waitress-9 : 500 Internal Server Error: The server encountered an internal error and was unable to complete your 
```

**Comment by gdaviet** [comment]
C'est du au fait que FlaskImages utilise `utcfromtimestamp`, qui n'est plus recommandé:

```
Warning

Because naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. As such, the recommended way to create an object representing a specific timestamp in UTC is by calling datetime.fromtimestamp(timestamp, tz=timezone.utc).
```
(https://docs.python.org/3/library/datetime.html)

J'ai un fix, @jnguiot  tu peux me donner les droit sur Club-Alpin-Annecy/FlaskImages ?

**Comment by jnguiot** [comment]
Je t'ai passé Owner de l'espace de travail: tu devrais avoir accès au dépot de Flask-Images
