### ISSUE TITLE
Erreur 500 à l'inscription

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives#632]
Version: v16.0
Conditions initiales:

* S'incrire  à la collective 6478

Comportement observé: Erreur 500
Comportement attendu: Inscription réussie

Stacktrace: 

```
2023-05-18 12:40:18,505 ERROR root waitress-7 : 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. datefmt=
Traceback (most recent call last):
  File "./.env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "./.env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "./.env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "./.env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./.env/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "./collectives/utils/access.py", line 57, in decorated_function
    return function(*args, **kwargs)
  File "./collectives/routes/event.py", line 669, in self_register
    conflicts = current_user.registrations_during(event.start, event.end, event_id)
  File "./collectives/models/user/misc.py", line 201, in registrations_during
    query = query.filter(Registration.event.has(id != excluded_event_id))
  File "./.env/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 564, in has
    return self.operate(PropComparator.has_op, criterion, **kwargs)
  File "./.env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 317, in operate
    return op(self.comparator, *other, **kwargs)
  File "./.env/lib/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 470, in has_op
    return a.has(b, **kwargs)
  File "./.env/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 1487, in has
    return self._criterion_exists(criterion, **kwargs)
  File "./.env/lib/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 1384, in _criterion_exists
    criterion = criterion._annotate(
AttributeError: 'bool' object has no attribute '_annotate'
```

**Comment by jnguiot** [comment]
Ce problème semble se produire sur tous les events... Problème de mysql?

**Comment by jnguiot** [comment]
Ce problème était lié aux pip qui n'était pas à jour, à cause du module pip qui était trop vieux et échouait. J'ai tout remis à jour
